// twopi-web/app/components/LabelAndValue.tsx
export default function LabelAndValue({
  label,
  value,
}: {
  label: string;
  value: React.ReactNode;
}) {
  return (
    <div className="flex flex-nowrap items-center gap-2">
      <div className="grow font-light">{label}</div>
      <div className="overflow-hidden text-sm text-nowrap text-ellipsis text-gray-700">
        {value}
      </div>
    </div>
  );
}

// twopi-ui/src/components/LabelAndValue.vue
<script setup lang="ts">
defineProps<{
  label: string;
}>();
</script>

<template>
  <div class="flex flex-nowrap items-center gap-2">
    <div class="grow font-light">{{ label }}</div>
    <div class="overflow-hidden text-ellipsis text-nowrap text-sm text-gray-700">
      <slot />
    </div>
  </div>
</template>
