// twopi-web/src/components/TransactionEditor.tsx
import { createForm } from "@tanstack/solid-form";
import { useMutation, useQuery, useQueryClient } from "@tanstack/solid-query";
import { useNavigate } from "@tanstack/solid-router";
import dayjs from "dayjs";
import { LucideTrash } from "lucide-solid";
import { For } from "solid-js";
import { createTransaction } from "~/lib/api/transaction";
import {
  accountQueryOptions,
  categoryQueryOptions,
  transactionByIdQueryOptions,
  transactionQueryOptions,
} from "~/lib/query-options";
import CurrencyInput from "./CurrencyInput";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import {
  Select,
  SelectContent,
  SelectHiddenSelect,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "./ui/select";

export default function TransactionEditor(
  props: Readonly<{
    edit?: {
      id: string;
      title: string;
      timestamp: Date;
      items: {
        id: string;
        notes: string;
        accountName: string;
        amount: number;
        categoryName?: string;
      }[];
    };
  }>,
) {
  const queryClient = useQueryClient();
  const navigate = useNavigate();
  const accountsQuery = useQuery(accountQueryOptions);
  const categoriesQuery = useQuery(categoryQueryOptions);

  const timestamp = new Date();
  timestamp.setMilliseconds(0);
  timestamp.setSeconds(0);
  const form = createForm(() => ({
    defaultValues: {
      id: props.edit?.id,
      title: props.edit?.title ?? "",
      transactions: props.edit?.items ?? [
        {
          notes: "",
          accountName: "",
          amount: 0,
          categoryName: "",
        },
      ],
      timestamp: props.edit?.timestamp ?? timestamp,
    },
    onSubmit({ value }) {
      mutation.mutate(value);
    },
  }));
  const mutation = useMutation(() => ({
    mutationFn: async (data: {
      id?: string;
      title: string;
      transactions: {
        id?: string;
        notes: string;
        accountName: string;
        amount: number;
        categoryName?: string;
      }[];
      timestamp: Date;
    }) => {
      await createTransaction(data);
      form.reset();
      navigate({
        to: "..",
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [
          transactionQueryOptions().queryKey,
          props.edit?.id
            ? transactionByIdQueryOptions(props.edit.id).queryKey
            : undefined,
        ],
      });
    },
  }));

  return (
    <div class="w-full">
      <form
        class="my-2 flex flex-col gap-4"
        onSubmit={(e) => {
          e.preventDefault();
          e.stopPropagation();
          form.handleSubmit();
        }}
      >
        <form.Field name="title">
          {(field) => (
            <Input
              type="text"
              placeholder="Name"
              name={field().name}
              value={field().state.value}
              onBlur={field().handleBlur}
              onChange={(e) => field().handleChange(e.target.value)}
            />
          )}
        </form.Field>
        <form.Field name="timestamp">
          {(field) => (
            <Input
              type="datetime-local"
              placeholder="Date/Time"
              name={field().name}
              value={dayjs(field().state.value).format("YYYY-MM-DDTHH:mm")}
              onBlur={field().handleBlur}
              onChange={(e) =>
                field().handleChange(dayjs(e.target.value).toDate())
              }
            />
          )}
        </form.Field>
        <form.Field name="transactions" mode="array">
          {(field) => (
            <div class="m-2 flex flex-col gap-4">
              <h2 class="text-lg">Transactions:</h2>
              <For each={field().state.value}>
                {(_, i) => (
                  <div class="flex gap-2">
                    <div class="flex grow flex-col gap-2">
                      <form.Field name={`transactions[${i()}].notes`}>
                        {(subField) => (
                          <Input
                            type="text"
                            placeholder="Name"
                            name={subField().name}
                            value={subField().state.value}
                            onBlur={subField().handleBlur}
                            onChange={(e) =>
                              subField().handleChange(e.target.value)
                            }
                          />
                        )}
                      </form.Field>
                      <form.Field name={`transactions[${i()}].accountName`}>
                        {(subField) => (
                          <Select
                            options={
                              accountsQuery.data?.accounts.map(
                                (a) => a.account.name,
                              ) ?? []
                            }
                            name={subField().name}
                            value={subField().state.value}
                            onChange={(e) => subField().handleChange(e ?? "")}
                            placeholder="Select account"
                            itemComponent={(props) => (
                              <SelectItem item={props.item}>
                                {props.item.rawValue}
                              </SelectItem>
                            )}
                          >
                            <SelectHiddenSelect />
                            <SelectTrigger>
                              <SelectValue<string>>
                                {(state) => state.selectedOption()}
                              </SelectValue>
                            </SelectTrigger>
                            <SelectContent />
                          </Select>
                        )}
                      </form.Field>
                      <form.Field name={`transactions[${i()}].amount`}>
                        {(subField) => (
                          <CurrencyInput
                            name={subField().name}
                            value={subField().state.value}
                            placeholder="Amount"
                            onBlur={subField().handleBlur}
                            onChange={subField().handleChange}
                            currencyCode={
                              accountsQuery.data?.accounts.find(
                                (a) =>
                                  a.account.name ===
                                  subField().form.state.values.transactions[i()]
                                    ?.accountName,
                              )?.currency.code ?? ""
                            }
                            decimalDigits={
                              accountsQuery.data?.accounts.find(
                                (a) =>
                                  a.account.name ===
                                  subField().form.state.values.transactions[i()]
                                    ?.accountName,
                              )?.currency.decimal_digits ?? 0
                            }
                          />
                        )}
                      </form.Field>
                      <form.Field name={`transactions[${i()}].categoryName`}>
                        {(subField) => (
                          <Select
                            options={
                              categoriesQuery.data?.categories.map(
                                (c) => c.name,
                              ) ?? []
                            }
                            name={subField().name}
                            value={subField().state.value}
                            onChange={(e) => subField().handleChange(e ?? "")}
                            placeholder="Select category"
                            itemComponent={(props) => (
                              <SelectItem item={props.item}>
                                {props.item.rawValue}
                              </SelectItem>
                            )}
                          >
                            <SelectHiddenSelect />
                            <SelectTrigger>
                              <SelectValue<string>>
                                {(state) => state.selectedOption()}
                              </SelectValue>
                            </SelectTrigger>
                            <SelectContent />
                          </Select>
                        )}
                      </form.Field>
                    </div>
                    <Button
                      variant="destructive"
                      onClick={() => field().removeValue(i())}
                    >
                      <LucideTrash />
                    </Button>
                  </div>
                )}
              </For>
              <Button
                type="button"
                variant="secondary"
                class="mt-2"
                onClick={() =>
                  field().pushValue({
                    notes: "",
                    accountName: "",
                    amount: 0,
                    categoryName: "",
                  })
                }
              >
                Add transaction
              </Button>
            </div>
          )}
        </form.Field>
        <form.Subscribe
          selector={(state) => [state.canSubmit, state.isSubmitting]}
        >
          {(val) => (
            <Button type="submit" disabled={!val()[0]}>
              {val()[1] ? "..." : props.edit ? "Update" : "Create"}
            </Button>
          )}
        </form.Subscribe>
        {mutation.isError && (
          <p class="text-destructive">{mutation.error?.message}</p>
        )}
      </form>
    </div>
  );
}

// twopi-ui/src/components/TransactionEditor.vue
<script setup lang="ts">
import { useAccountsQuery } from "@/lib/account";
import { useCategoryQuery } from "@/lib/category";
import { useCreateTransaactionMutation } from "@/lib/transaction";
import type { FormSubmitEvent } from "@nuxt/ui";
import dayjs from "dayjs";
import z from "zod";

const props = defineProps<{
  transaction?: {
    id: string;
    title: string;
    timestamp: Date;
    items: {
      id: string;
      notes: string;
      accountName: string;
      amount: number;
      categoryName?: string;
    }[];
  };
}>();

const timestamp = new Date();
timestamp.setMilliseconds(0);
timestamp.setSeconds(0);

const { data: accounts } = useAccountsQuery();
const { data: categories } = useCategoryQuery();

const router = useRouter();
const itemSchema = z.object({
  id: z.string().optional(),
  notes: z.string(),
  accountName: z.string(),
  amount: z.number(),
  categoryName: z.string().optional(),
});
const schema = z.object({
  title: z.string(),
  timestamp: z.date(),
  items: z.array(itemSchema),
});
type FormState = z.infer<typeof schema>;

const state = reactive<FormState>({
  title: props.transaction?.title || "",
  timestamp: props.transaction?.timestamp || timestamp,
  items: props.transaction?.items || [],
});

const { error, mutateAsync } = useCreateTransaactionMutation();

async function createTransaction(event: FormSubmitEvent<FormState>) {
  const done = await mutateAsync({
    id: props.transaction?.id,
    title: event.data.title,
    timestamp: event.data.timestamp,
    transactions: event.data.items.map((item) => ({
      ...item,
      categoryName: item.categoryName === "" ? undefined : item.categoryName,
    })),
  });
  if (done.success) {
    router.push({
      name: "/app/finance/transaction/",
    });
  }
}
</script>

<template>
  <UForm :state="state" :schema="schema" class="space-y-4" @submit="createTransaction">
    <UFormField label="Title" name="title">
      <UInput v-model="state.title" class="w-full" />
    </UFormField>
    <UFormField label="Timestamp" name="timestamp">
      <UInput
        :model-value="dayjs(state.timestamp).format('YYYY-MM-DDTHH:mm')"
        type="datetime-local"
        class="w-full"
        @update:model-value="($event) => (state.timestamp = dayjs($event).toDate())"
      />
    </UFormField>
    <div class="my-2 space-y-4">
      <h2 class="text-lg">Transactions:</h2>
      <UForm
        v-for="(item, index) in state.items"
        :key="index"
        :state="item"
        :schema="itemSchema"
        attach
      >
        <UCard>
          <UFormField label="Notes" name="notes">
            <UInput v-model="item.notes" class="w-full" />
          </UFormField>
          <UFormField label="Account" name="accountName">
            <USelectMenu
              v-model="item.accountName"
              :items="accounts?.accounts.map((a) => a.account.name)"
              class="w-full"
            />
          </UFormField>
          <UFormField label="Amount" name="amount">
            <UInputNumber
              v-model="item.amount"
              class="w-full"
              :format-options="{
                style: 'currency',
                currency:
                  accounts?.accounts.find((a) => a.account.name === item.accountName)?.account
                    .currency_code || 'USD',
                currencyDisplay: 'code',
                currencySign: 'standard',
              }"
            />
          </UFormField>
          <UFormField label="Category" name="categoryName">
            <USelectMenu
              v-model="item.categoryName"
              :items="categories?.categories.map((c) => c.name)"
              class="w-full"
            />
          </UFormField>
          <UButton type="button" color="error" class="mt-2" @click="state.items.splice(index, 1)">
            <UIcon name="i-lucide-trash" />
          </UButton>
        </UCard>
      </UForm>
      <UButton
        type="button"
        variant="outline"
        @click="state.items.push({ notes: '', accountName: '', amount: 0, categoryName: '' })"
      >
        Add transaction
      </UButton>
    </div>
    <UButton v-if="transaction" type="submit"> <UIcon name="i-lucide-save" /> Save </UButton>
    <UButton v-else type="submit"> <UIcon name="i-lucide-plus" /> Create </UButton>
    <p v-if="error" class="text-error">{{ error?.message }}</p>
  </UForm>
</template>
