// twopi-web/src/routes/app/finance/account/index.tsx
import { useQuery } from "@tanstack/solid-query";
import { createFileRoute, Link, useNavigate } from "@tanstack/solid-router";
import { Check, Plus, X } from "lucide-solid";
import { createMemo, For } from "solid-js";
import { AccountTypeIcon } from "~/components/AccountTypeIcon";
import CurrencyDisplay from "~/components/CurrencyDisplay";
import { PageLayout } from "~/components/PageLayout";
import QueryWrapper from "~/components/QueryWrapper";
import { Badge } from "~/components/ui/badge";
import { buttonVariants } from "~/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "~/components/ui/table";
import { type getAccounts } from "~/lib/api/account";
import type { AccountTypeOrigin } from "~/lib/hacks/account-type";
import {
  accountQueryOptions,
  transactionQueryOptions,
} from "~/lib/query-options";

export const Route = createFileRoute("/app/finance/account/")({
  component: RouteComponent,
});

type Account = Awaited<ReturnType<typeof getAccounts>>["accounts"][number];

function RouteComponent() {
  const navigate = useNavigate();
  const accountsQuery = useQuery(accountQueryOptions);
  const transactionsQuery = useQuery(transactionQueryOptions);

  const filteredTransactions = createMemo(() => {
    if (!transactionsQuery.data || !accountsQuery.data) {
      return [];
    }
    return transactionsQuery.data.transactions?.filter((transaction) => {
      return (
        transaction.items?.some((item) =>
          accountsQuery.data.accounts.some(
            (account) => account.account.id === item.account_id,
          ),
        ) ?? false
      );
    });
  });

  function calculateBalance(account: Account) {
    return (
      account.account.starting_balance +
      (filteredTransactions()
        ?.map((transaction) => {
          let amount = 0;
          for (const item of transaction.items) {
            if (item.account_id === account.account.id) {
              amount += item.amount;
            }
          }
          return amount;
        })
        .reduce((acc, curr) => acc + curr, 0) ?? 0)
    );
  }

  return (
    <PageLayout
      title="Account"
      actions={
        <Link
          to="/app/finance/account/new"
          class={buttonVariants({
            variant: "outline",
            size: "icon",
          })}
        >
          <Plus />
        </Link>
      }
    >
      <QueryWrapper
        queryResult={accountsQuery}
        errorRender={(e) => <div>{e.message}</div>}
      >
        {(data) => (
          <Table>
            <TableHeader>
              <TableRow class="*:py-2">
                <TableHead>Name</TableHead>
                <TableHead>Type</TableHead>
                <TableHead class="text-right">Starting balance</TableHead>
                <TableHead class="text-right">Cash flow</TableHead>
                <TableHead class="text-right">Active</TableHead>
                <TableHead class="text-right">Created at</TableHead>
                <TableHead class="text-right">Current balance</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <For
                each={data.accounts}
                fallback={<div>No accounts found.</div>}
              >
                {(account) => (
                  <TableRow
                    onClick={() => {
                      navigate({
                        to: "/app/finance/account/$id",
                        params: {
                          id: account.account.id,
                        },
                      });
                    }}
                    class="cursor-pointer *:py-2"
                  >
                    <TableCell>{account.account.name}</TableCell>
                    <TableCell>
                      <Badge variant="outline">
                        <AccountTypeIcon
                          type={
                            account.account.account_type as AccountTypeOrigin
                          }
                        />
                        {account.account.account_type}
                      </Badge>
                    </TableCell>
                    <TableCell class="text-right">
                      <CurrencyComp
                        value={account.account.starting_balance}
                        currencyCode={account.account.currency_code}
                        decimalDigits={account.currency.decimal_digits}
                      />
                    </TableCell>
                    <TableCell class="text-right">
                      {account.account.is_cash_flow ? (
                        <Check class="inline" />
                      ) : (
                        <X class="inline" />
                      )}
                    </TableCell>
                    <TableCell class="text-right">
                      {account.account.is_active ? (
                        <Check class="inline" />
                      ) : (
                        <X class="inline" />
                      )}
                    </TableCell>
                    <TableCell class="text-right">
                      {Intl.DateTimeFormat("en-IN", {
                        dateStyle: "medium",
                      }).format(new Date(account.account.created_at))}
                    </TableCell>
                    <TableCell class="text-right">
                      <CurrencyComp
                        value={calculateBalance(account)}
                        currencyCode={account.account.currency_code}
                        decimalDigits={account.currency.decimal_digits}
                      />
                    </TableCell>
                  </TableRow>
                )}
              </For>
            </TableBody>
          </Table>
        )}
      </QueryWrapper>
    </PageLayout>
  );
}

function CurrencyComp(
  props: Readonly<{
    value: number;
    currencyCode: string;
    decimalDigits: number;
  }>,
) {
  return (
    <Badge
      class={
        props.value < 0
          ? "border-red-600 bg-red-200 text-red-900"
          : props.value > 0
            ? "border-green-600 bg-green-200 text-green-900"
            : "border-gray-600 bg-gray-200 text-gray-900"
      }
    >
      <CurrencyDisplay
        value={props.value}
        currencyCode={props.currencyCode}
        decimalDigits={props.decimalDigits}
      />
    </Badge>
  );
}

// twopi-ui/src/pages/app/finance/account/index.vue
<script setup lang="ts">
import { useAccountsQuery } from "@/lib/account";
import { useDeleteCategoryMutation } from "@/lib/category";
import { iconMap } from "@/lib/hacks/account-type";
import type { Paths } from "@/lib/openapi";
import { useTransactionsQuery } from "@/lib/transaction";
import dayjs from "dayjs";

const { mutate } = useDeleteCategoryMutation();
const { data: transactions } = useTransactionsQuery();

const query = useAccountsQuery();
const router = useRouter();

type Account = NonNullable<
  Paths["/twopi-api/account/{account_id}"]["get"]["responses"]["200"]["content"]["application/json"]
>;

const filteredTransactions = computed(() => {
  if (!transactions.value?.transactions || !query.data.value?.accounts) {
    return [];
  }
  return transactions.value.transactions?.filter((transaction) => {
    return (
      transaction.items?.some((item) =>
        query.data.value?.accounts.some((account) => account.account.id === item.account_id),
      ) ?? false
    );
  });
});

function calculateBalance(account: Account) {
  return (
    account.account.starting_balance +
    (filteredTransactions.value
      ?.map((transaction) => {
        let amount = 0;
        for (const item of transaction.items) {
          if (item.account_id === account.account.id) {
            amount += item.amount;
          }
        }
        return amount;
      })
      .reduce((acc, curr) => acc + curr, 0) ?? 0)
  );
}
</script>

<template>
  <AppPage title="Account">
    <template #actions>
      <UButton
        @click="
          () => {
            router.push({ name: '/app/finance/account/new' });
          }
        "
      >
        <UIcon name="i-lucide-plus" /> Add
      </UButton>
    </template>
    <QueryWrapper
      v-slot="{ data: accounts }"
      :data="query"
      :transform="(data) => data.accounts"
      class="space-y-4"
    >
      <UCard v-for="item in accounts" :key="item.account.id">
        <div class="flex">
          <div>{{ item.account.name }}</div>
          <UBadge class="mx-2" :icon="iconMap[item.account.account_type]">{{
            item.account.account_type
          }}</UBadge>
          <div class="flex-1"></div>
          <div class="flex space-x-2">
            <UButton
              variant="outline"
              color="primary"
              @click="
                () => {
                  router.push({
                    name: '/app/finance/account/[id]',
                    params: { id: item.account.id },
                  });
                }
              "
            >
              <UIcon name="i-lucide-eye" />
            </UButton>
            <UButton
              variant="outline"
              color="secondary"
              @click="
                () => {
                  router.push({
                    name: '/app/finance/account/[id].edit',
                    params: { id: item.account.id },
                  });
                }
              "
            >
              <UIcon name="i-lucide-edit" />
            </UButton>
            <UButton variant="outline" color="error" @click="() => mutate(item.account.id)">
              <UIcon name="i-lucide-trash" />
            </UButton>
          </div>
        </div>
        <div class="mt-2 flex gap-2">
          <UBadge variant="outline">
            <CurrencyDisplay
              :value="calculateBalance(item)"
              :currency-code="item.currency.code"
              :decimal-digits="item.currency.decimal_digits"
            />
          </UBadge>
          <UBadge v-if="item.account.is_active" variant="soft" color="success">Active</UBadge>
          <UBadge v-if="item.account.is_cash_flow" variant="soft" color="neutral">Cash flow</UBadge>
          <div class="flex-1"></div>
          <UBadge variant="soft">
            {{ dayjs(item.account.created_at).format("D MMM YYYY") }}
          </UBadge>
        </div>
      </UCard>
    </QueryWrapper>
  </AppPage>
</template>
