// twopi-web/app/routes/signin.tsx
import { useForm } from "@tanstack/react-form";
import { createFileRoute, useRouter } from "@tanstack/react-router";
import { zodValidator } from "@tanstack/zod-adapter";
import { useState } from "react";
import { z } from "zod";
import { Button } from "~/components/ui/button";
import { authClient } from "~/lib/auth-client";

const signinSearchParamsSchema = z.object({
  redirect: z.string().optional(),
});

export const Route = createFileRoute("/signin")({
  component: RouteComponent,
  validateSearch: zodValidator(signinSearchParamsSchema),
  loader: async ({ context }) => {
    return { session: context.session };
  },
});

function RouteComponent() {
  const state = Route.useLoaderData();
  const search = Route.useSearch();
  const router = useRouter();
  const [signInError, setSignInError] = useState<string | undefined>();
  const [signUpError, setSignUpError] = useState<string | undefined>();
  const signInForm = useForm({
    defaultValues: {
      email: "",
      password: "",
    },
    onSubmit: async ({ value }) => {
      const { error } = await authClient.signIn.email(value);
      if (error) {
        setSignInError(error.message);
      } else {
        await router.invalidate();
        if (search.redirect) {
          router.navigate({ to: search.redirect });
        } else {
          router.navigate({ to: "/" });
        }
      }
    },
  });
  const signUpForm = useForm({
    defaultValues: {
      name: "",
      email: "",
      password: "",
    },
    onSubmit: async ({ value }) => {
      const { error } = await authClient.signUp.email(value);
      if (error) {
        setSignUpError(error.message);
      } else {
        await router.invalidate();
        if (search.redirect) {
          router.navigate({ to: search.redirect });
        } else {
          router.navigate({ to: "/" });
        }
      }
    },
  });

  if (state.session?.user) {
    if (search.redirect) {
      router.navigate({ to: search.redirect });
    }
    return <div>You are already signed in</div>;
  }

  return (
    <div className="m-4 flex w-full gap-4">
      <div className="flex grow flex-col gap-4">
        <h1 className="text-xl font-bold">Sign in</h1>
        <form
          className="flex flex-col gap-4"
          onSubmit={(e) => {
            e.preventDefault();
            e.stopPropagation();
            signInForm.handleSubmit();
          }}
        >
          <signInForm.Field name="email">
            {(field) => (
              <input
                type="email"
                placeholder="Email"
                name={field.name}
                value={field.state.value}
                onBlur={field.handleBlur}
                onChange={(e) => field.handleChange(e.target.value)}
              />
            )}
          </signInForm.Field>
          <signInForm.Field name="password">
            {(field) => (
              <input
                type="password"
                placeholder="Password"
                name={field.name}
                value={field.state.value}
                onBlur={field.handleBlur}
                onChange={(e) => field.handleChange(e.target.value)}
              />
            )}
          </signInForm.Field>
          <div className="text-red-600">{signInError}</div>
          <Button type="submit" variant="default">
            Sign in
          </Button>
        </form>
      </div>
      <div className="flex grow flex-col gap-4">
        <h1 className="text-xl font-bold">Sign up</h1>
        <form
          className="flex flex-col gap-4"
          onSubmit={(e) => {
            e.preventDefault();
            e.stopPropagation();
            signUpForm.handleSubmit();
          }}
        >
          <signUpForm.Field name="name">
            {(field) => (
              <input
                type="text"
                placeholder="Name"
                name={field.name}
                value={field.state.value}
                onBlur={field.handleBlur}
                onChange={(e) => field.handleChange(e.target.value)}
              />
            )}
          </signUpForm.Field>
          <signUpForm.Field name="email">
            {(field) => (
              <input
                type="email"
                placeholder="Email"
                name={field.name}
                value={field.state.value}
                onBlur={field.handleBlur}
                onChange={(e) => field.handleChange(e.target.value)}
              />
            )}
          </signUpForm.Field>
          <signUpForm.Field name="password">
            {(field) => (
              <input
                type="password"
                placeholder="Password"
                name={field.name}
                value={field.state.value}
                onBlur={field.handleBlur}
                onChange={(e) => field.handleChange(e.target.value)}
              />
            )}
          </signUpForm.Field>
          <div className="text-red-600">{signUpError}</div>
          <Button type="submit" variant="default">
            Sign up
          </Button>
        </form>
      </div>
    </div>
  );
}

// twopi-ui/src/pages/signin.vue
<script setup lang="ts">
import { useAuthUser, useSignIn, useSignUp } from "@/lib/auth";
import type { FormSubmitEvent } from "@nuxt/ui";
import z from "zod";

const route = useRoute();
const router = useRouter();

const signInSchema = z.object({
  email: z.email("Invalid email address"),
  password: z.string().min(8, "Password must be at least 8 characters long"),
});
type SignInForm = z.infer<typeof signInSchema>;

const signUpSchema = z.object({
  name: z.string().min(1, "Name is required"),
  email: z.email("Invalid email address"),
  password: z.string().min(8, "Password must be at least 8 characters long"),
});
type SignUpForm = z.infer<typeof signUpSchema>;

const signInState = reactive<Partial<SignInForm>>({
  email: "",
  password: "",
});

const signUpState = reactive<Partial<SignUpForm>>({
  name: "",
  email: "",
  password: "",
});

const { mutate: signIn, error: signInError } = useSignIn();
const { mutate: signUp, error: signUpError } = useSignUp();

function onSignIn(event: FormSubmitEvent<SignInForm>) {
  signIn({
    email: event.data.email,
    password: event.data.password,
  });
}

function onSignUp(event: FormSubmitEvent<SignUpForm>) {
  signUp({
    name: event.data.name,
    email: event.data.email,
    password: event.data.password,
  });
}

const { data: session } = useAuthUser();
const user = computed(() => session.value?.user);

watchEffect(() => {
  if (user.value) {
    if (route.query.next) {
      router.push(route.query.next as string);
    } else {
      router.push({
        name: "/app/",
      });
    }
  }
});
</script>

<template>
  <div v-if="user">
    <div>You are already signed in.</div>
  </div>
  <div v-else class="flex flex-col gap-4 p-4">
    <div class="flex-1">
      <h2 class="mb-4 text-2xl font-bold">Sign In</h2>
      <UForm :schema="signInSchema" :state="signInState" class="space-y-4" @submit="onSignIn">
        <UFormField label="Email" name="email">
          <UInput v-model="signInState.email" class="w-full" />
        </UFormField>

        <UFormField label="Password" name="password">
          <UInput v-model="signInState.password" type="password" class="w-full" />
        </UFormField>

        <UButton type="submit"> Submit </UButton>

        <p v-if="signInError" class="text-red-600">{{ signInError }}</p>
      </UForm>
    </div>
    <div class="flex-1">
      <h2 class="mb-4 text-2xl font-bold">Sign Up</h2>
      <UForm :schema="signUpSchema" :state="signUpState" class="space-y-4" @submit="onSignUp">
        <UFormField label="Name" name="name">
          <UInput v-model="signUpState.name" class="w-full" />
        </UFormField>

        <UFormField label="Email" name="email">
          <UInput v-model="signUpState.email" class="w-full" />
        </UFormField>

        <UFormField label="Password" name="password">
          <UInput v-model="signUpState.password" type="password" class="w-full" />
        </UFormField>

        <UButton type="submit"> Submit </UButton>

        <p v-if="signUpError" class="text-red-600">{{ signUpError }}</p>
      </UForm>
    </div>
  </div>
</template>
