// twopi-ui/src/pages/app/finance/category/new.vue
<script setup lang="ts">
const router = useRouter();
</script>

<template>
  <AppPage title="New Category">
    <template #actions>
      <UButton
        variant="ghost"
        @click="
          () => {
            router.push({
              name: '/app/finance/category/',
            });
          }
        "
      >
        <UIcon name="i-lucide-arrow-left" /> All
      </UButton>
    </template>
    <CategoryEditor />
  </AppPage>
</template>

// twopi-web/src/routes/app/category/new.tsx
import { createFileRoute, Link } from "@tanstack/solid-router";
import { ArrowLeft } from "lucide-solid";
import CategoryEditor from "~/components/CategofyEditor";
import { PageLayout } from "~/components/PageLayout";

export const Route = createFileRoute("/app/category/new")({
  component: RouteComponent,
});

function RouteComponent() {
  return (
    <PageLayout
      title="New Category"
      actions={
        <Link to="..">
          <ArrowLeft />
        </Link>
      }
    >
      <CategoryEditor />
    </PageLayout>
  );
}
