// twopi-ui/src/components/AccountEditor.vue
<script setup lang="ts">
import { useCreateAccountMutation } from "@/lib/account";
import { useCurrencyQuery } from "@/lib/currency";
import { AccountType, type AccountTypeOrigin } from "@/lib/hacks/account-type";
import type { FormSubmitEvent } from "@nuxt/ui";
import dayjs from "dayjs";
import z from "zod";

const props = defineProps<{
  account?: {
    id: string;
    name: string;
    accountType: AccountTypeOrigin;
    createdAt: Date;
    currencyCode: string;
    startingBalance: number;
    isCashFlow: boolean;
    isActive: boolean;
  };
}>();

const router = useRouter();
const { data: currencies } = useCurrencyQuery();

const createdAt = new Date();
createdAt.setMilliseconds(0);
createdAt.setSeconds(0);

const schema = z.object({
  name: z.string().min(1, "Name is required"),
  accountType: z.enum(AccountType),
  createdAt: z.date(),
  currencyCode: z.string().min(1, "Currency code is required"),
  startingBalance: z.number(),
  isCashFlow: z.boolean(),
  isActive: z.boolean(),
});
type FormState = z.infer<typeof schema>;
const state = reactive<FormState>({
  name: props.account?.name ?? "",
  accountType: props.account?.accountType ?? "Bank",
  createdAt: props.account?.createdAt ?? createdAt,
  currencyCode: props.account?.currencyCode ?? "USD",
  startingBalance: props.account?.startingBalance ?? 0,
  isCashFlow: props.account?.isCashFlow ?? false,
  isActive: props.account?.isActive ?? true,
});

const { error, mutateAsync } = useCreateAccountMutation();

async function createAccount(event: FormSubmitEvent<FormState>) {
  const done = await mutateAsync({
    id: props.account?.id,
    name: event.data.name,
    accountType: event.data.accountType,
    createdAt: event.data.createdAt,
    currencyCode: event.data.currencyCode,
    startingBalance: event.data.startingBalance,
    isCashFlow: event.data.isCashFlow,
    isActive: event.data.isActive,
  });
  if (done.success) {
    router.push({
      name: "/app/finance/account/",
    });
  }
}
</script>

<template>
  <UForm :state="state" :schema="schema" class="space-y-4" @submit="createAccount">
    <UFormField label="Name" name="name">
      <UInput v-model="state.name" class="w-full" />
    </UFormField>
    <UFormField label="Account Type" name="accountType">
      <USelectMenu v-model="state.accountType" :items="Object.values(AccountType)" class="w-full" />
    </UFormField>
    <UFormField label="Created At" name="createdAt">
      <UInput
        :model-value="dayjs(state.createdAt).format('YYYY-MM-DDTHH:mm')"
        type="datetime-local"
        class="w-full"
        @update:model-value="($event) => (state.createdAt = dayjs($event).toDate())"
      />
    </UFormField>
    <UFormField label="Currency Code" name="currencyCode">
      <USelectMenu
        v-model="state.currencyCode"
        :items="
          currencies?.currency.map((c) => ({
            label: `${c.code} - ${c.name}`,
            value: c.code,
          }))
        "
        :value-key="'value'"
        class="w-full"
      />
    </UFormField>
    <UFormField label="Starting Balance" name="startingBalance">
      <UInputNumber
        v-model="state.startingBalance"
        :format-options="{
          style: 'currency',
          currency: state.currencyCode,
          currencyDisplay: 'code',
          currencySign: 'standard',
        }"
        class="w-full"
      />
    </UFormField>
    <UFormField name="isCashFlow">
      <UCheckbox v-model="state.isCashFlow" label="Is cash flow?" />
    </UFormField>
    <UFormField name="isActive">
      <UCheckbox v-model="state.isActive" label="Is active?" />
    </UFormField>
    <UButton v-if="account" type="submit"> <UIcon name="i-lucide-save" /> Save </UButton>
    <UButton v-else type="submit"> <UIcon name="i-lucide-plus" /> Create </UButton>
    <p v-if="error" class="text-error">{{ error?.message }}</p>
  </UForm>
</template>

// twopi-web/app/components/AccountEditor.tsx
import { useForm } from "@tanstack/react-form";
import { useMutation, useQueries, useQueryClient } from "@tanstack/react-query";
import { Link, useNavigate } from "@tanstack/react-router";
import dayjs from "dayjs";
import { AccountType, type AccountTypeOrigin } from "~/lib/hacks/account-type";
import { accountQueryOptions, currencyQueryOptions } from "~/lib/query-options";
import { createAccount } from "~/lib/server-fns/account";
import { isDefined } from "~/lib/utils";

export default function AccountEditor(props: {
  edit?: {
    id: string;
    name: string;
    accountType: AccountTypeOrigin;
    createdAt: Date;
    currencyCode: string;
    startingBalance: number;
  };
}) {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const { isPending, errors, data } = useQueries({
    queries: [currencyQueryOptions()],
    combine: (results) => {
      return {
        data: {
          currencies: results[0].data?.data,
        },
        isPending: results.some((result) => result.isPending),
        errors: results.map((result) => result.error).filter(isDefined),
      };
    },
  });

  const createdAt = new Date();
  createdAt.setMilliseconds(0);
  createdAt.setSeconds(0);
  const form = useForm({
    defaultValues: {
      id: props.edit?.id,
      name: props.edit?.name || "",
      accountType: props.edit?.accountType || "",
      createdAt: props.edit?.createdAt || createdAt,
      currencyCode: props.edit?.currencyCode || "",
      startingBalance: props.edit?.startingBalance || 0,
    },
    onSubmit: ({ value }) => {
      mutation.mutate(value);
    },
  });
  const mutation = useMutation({
    mutationFn: async (data: unknown) => {
      createAccount({ data });
      form.reset();
      navigate({
        to: "..",
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: accountQueryOptions().queryKey,
      });
    },
  });

  if (isPending) return "Loading...";
  if (errors.length)
    return (
      <div>
        Error occurred:
        {errors.map((error, i) => (
          <div key={i}>{error.message}</div>
        ))}
      </div>
    );

  return (
    <div className="w-full">
      <div className="flex items-center gap-2">
        <h1 className="my-2 grow text-xl font-bold">
          {props.edit ? "Edit" : "New"} Account
        </h1>
        <Link to=".." className="d-btn d-btn-sm d-btn-secondary">
          Back
        </Link>
      </div>
      <form
        className="my-2 flex flex-col gap-4"
        onSubmit={(e) => {
          e.preventDefault();
          e.stopPropagation();
          form.handleSubmit();
        }}
      >
        <form.Field name="name">
          {(field) => (
            <input
              type="text"
              className="w-full"
              placeholder="Name"
              name={field.name}
              value={field.state.value}
              onBlur={field.handleBlur}
              onChange={(e) => field.handleChange(e.target.value)}
            />
          )}
        </form.Field>
        <form.Field name="accountType">
          {(field) => (
            <select
              className="w-full"
              name={field.name}
              value={field.state.value}
              onBlur={field.handleBlur}
              onChange={(e) => field.handleChange(e.target.value)}
            >
              <option disabled value="">
                Select account type
              </option>
              {Object.values(AccountType).map((type) => (
                <option key={type} value={type}>
                  {type}
                </option>
              ))}
            </select>
          )}
        </form.Field>
        <form.Field name="createdAt">
          {(field) => (
            <input
              type="datetime-local"
              className="w-full"
              placeholder="Date/Time"
              name={field.name}
              value={dayjs(field.state.value).format("YYYY-MM-DDTHH:mm")}
              onBlur={field.handleBlur}
              onChange={(e) =>
                field.handleChange(dayjs(e.target.value).toDate())
              }
            />
          )}
        </form.Field>
        <form.Field name="currencyCode">
          {(field) => (
            <select
              className="select w-full"
              name={field.name}
              value={field.state.value}
              onBlur={field.handleBlur}
              onChange={(e) => field.handleChange(e.target.value)}
            >
              <option disabled value="">
                Select currency
              </option>
              {data.currencies?.map((currency) => (
                <option key={currency.code} value={currency.code}>
                  {currency.code} - {currency.name}
                </option>
              ))}
            </select>
          )}
        </form.Field>
        <form.Field name="startingBalance">
          {(field) => (
            <input
              type="text"
              className="w-full"
              placeholder="Starting Balance"
              name={field.name}
              value={field.state.value}
              onBlur={field.handleBlur}
              onChange={(e) => field.handleChange(Number(e.target.value))}
            />
          )}
        </form.Field>
        <button
          type="submit"
          className="d-btn d-btn-primary"
          disabled={mutation.isPending}
        >
          {props.edit ? "Update" : "Create"}
        </button>
        {mutation.isPending && <p className="text-info-content">Creating...</p>}
        {mutation.isError && (
          <p className="text-error-content">{mutation.error?.message}</p>
        )}
      </form>
    </div>
  );
}
