// twopi-web/src/components/LabelAndValue.tsx
import type { JSX } from "solid-js";

export default function LabelAndValue(
  props: Readonly<{
    label: string;
    value: JSX.Element;
  }>,
) {
  return (
    <div class="flex flex-nowrap items-center gap-2">
      <div class="grow font-light">{props.label}</div>
      <div class="overflow-hidden text-ellipsis text-nowrap text-sm text-gray-700">
        {props.value}
      </div>
    </div>
  );
}

// twopi-web/app/components/LabelAndValue.tsx
export default function LabelAndValue({
  label,
  value,
}: {
  label: string;
  value: React.ReactNode;
}) {
  return (
    <div className="flex flex-nowrap items-center gap-2">
      <div className="grow font-light">{label}</div>
      <div className="overflow-hidden text-sm text-nowrap text-ellipsis text-gray-700">
        {value}
      </div>
    </div>
  );
}
