// khata-ui/src/components/CurrencyDisplay.vue
<script setup lang="ts">
const props = defineProps<{
  value: number;
  currencyCode: string;
  decimalDigits: number;
}>();

const amount = computed(() => props.value / Math.pow(10, props.decimalDigits));
</script>

<template>
  <div>
    {{
      Intl.NumberFormat("en-US", {
        style: "currency",
        currency: props.currencyCode,
      }).format(amount)
    }}
  </div>
</template>

// twopi-web/src/components/CurrencyDisplay.tsx
export default function CurrencyDisplay(
  props: Readonly<{
    value: number;
    currencyCode: string;
    decimalDigits: number;
  }>,
) {
  const amount = () => props.value / Math.pow(10, props.decimalDigits);
  return (
    <div>
      {Intl.NumberFormat("en-US", {
        style: "currency",
        currency: props.currencyCode,
      }).format(amount())}
    </div>
  );
}
