// khata-ui/src/components/TransactionRow.vue
<script setup lang="ts">
import { useAccountsQuery } from "@/lib/account";
import { useCategoryQuery } from "@/lib/category";
import { iconMap } from "@/lib/hacks/account-type";
import type { Paths } from "@/lib/openapi";
import dayjs from "dayjs";

type Transaction = NonNullable<
  Paths["/khata-api/transaction/{transaction_id}"]["get"]["responses"]["200"]["content"]["application/json"]
>;

const props = defineProps<{
  transaction: Readonly<Transaction>;
}>();

const { data: accounts } = useAccountsQuery();
const { data: categories } = useCategoryQuery();
const account = (id: string) => {
  return accounts.value?.accounts.find((a) => a.account.id === id);
};
const category = (id?: string | null) => {
  return categories.value?.categories.find((c) => c.id === id);
};
</script>

<template>
  <UCard>
    <ULink
      :to="{
        name: '/app/finance/transaction/[id]',
        params: {
          id: props.transaction.transaction.id,
        },
      }"
      class="flex flex-col gap-2"
    >
      <div class="flex gap-2">
        <h2 class="grow overflow-hidden text-ellipsis text-nowrap">
          {{ props.transaction.transaction.title }}
        </h2>
        <div class="flex gap-2 text-sm">
          {{ dayjs(props.transaction.transaction.timestamp).format("h:mm A") }}
        </div>
      </div>
      <div class="flex flex-col gap-2">
        <div v-for="item in props.transaction.items" :key="item.id" class="flex items-center gap-2">
          <div class="grow overflow-hidden text-ellipsis text-nowrap text-sm">
            <LocalScope v-slot="{ scope }" :scope="category(item.category_id)">
              <UBadge v-if="scope" variant="soft" class="text-nowrap" :icon="scope.icon">{{
                scope.name
              }}</UBadge>
            </LocalScope>
            {{ item.notes }}
          </div>
          <LocalScope v-slot="{ scope }" :scope="account(item.account_id)">
            <UBadge
              v-if="scope"
              variant="outline"
              :icon="iconMap[scope.account.account_type]"
              class="text-nowrap"
              >{{ scope.account.name }}</UBadge
            >
            <UBadge
              v-if="scope"
              class="text-nowrap"
              :color="item.amount < 0 ? 'error' : item.amount > 0 ? 'success' : 'neutral'"
            >
              <CurrencyDisplay
                :value="item.amount"
                :currency-code="scope.currency.code"
                :decimal-digits="scope.currency.decimal_digits"
              />
            </UBadge>
          </LocalScope>
        </div>
      </div>
    </ULink>
  </UCard>
</template>
;

// twopi-web/src/components/TransactionRow.tsx
import { useQuery } from "@tanstack/solid-query";
import { Link } from "@tanstack/solid-router";
import dayjs from "dayjs";
import { For, Show } from "solid-js";
import { type getTransaction } from "~/lib/api/transaction";
import type { AccountTypeOrigin } from "~/lib/hacks/account-type";
import { accountQueryOptions, categoryQueryOptions } from "~/lib/query-options";
import { AccountTypeIcon } from "./AccountTypeIcon";
import CurrencyDisplay from "./CurrencyDisplay";
import DynamicIcon from "./DynamicIcon";
import { Badge } from "./ui/badge";

type Transaction = Awaited<ReturnType<typeof getTransaction>>;

export default function TransactionRow(
  props: Readonly<{ transaction: Transaction }>,
) {
  const accountsQuery = useQuery(accountQueryOptions);
  const categoriesQuery = useQuery(categoryQueryOptions);
  const account = (id: string) =>
    accountsQuery.data?.accounts.find((account) => account.account.id === id);
  const category = (id?: string | null) =>
    categoriesQuery.data?.categories.find((category) => category.id === id);

  return (
    <div class="border-1 rounded-2xl p-3">
      <Link
        to="/app/finance/transaction/$id"
        params={{ id: props.transaction.transaction.id }}
        class="flex flex-col gap-2"
      >
        <div class="flex gap-2">
          <h2 class="grow overflow-hidden text-ellipsis text-nowrap">
            {props.transaction.transaction.title}
          </h2>
          <div class="flex gap-2 text-sm text-zinc-700">
            {dayjs(props.transaction.transaction.timestamp).format("h:mm A")}
          </div>
        </div>
        <div class="flex flex-col gap-2">
          {
            <For each={props.transaction.items}>
              {(item) => (
                <div class="flex items-center gap-2">
                  <div class="grow overflow-hidden text-ellipsis text-nowrap text-sm text-gray-500">
                    <Show when={category(item.category_id)}>
                      {(category) => (
                        <Badge variant="secondary" class="mr-2">
                          {item.category_id && (
                            <DynamicIcon
                              name={category().icon as "Loader"}
                              class="inline-block h-4 w-4"
                            />
                          )}
                          {category().name}
                        </Badge>
                      )}
                    </Show>

                    {item.notes}
                  </div>
                  <Badge variant="outline">
                    <Show when={account(item.account_id)}>
                      {(account) => (
                        <AccountTypeIcon
                          type={
                            account().account.account_type as AccountTypeOrigin
                          }
                        />
                      )}
                    </Show>
                    {account(item.account_id)?.account.name}
                  </Badge>
                  <Badge
                    class={
                      item.amount < 0
                        ? "border-red-600 bg-red-200 text-red-900"
                        : item.amount > 0
                          ? "border-green-600 bg-green-200 text-green-900"
                          : "border-gray-600 bg-gray-200 text-gray-900"
                    }
                  >
                    <Show when={account(item.account_id)}>
                      {(account) => (
                        <CurrencyDisplay
                          value={item.amount}
                          currencyCode={account().currency.code}
                          decimalDigits={account().currency.decimal_digits}
                        />
                      )}
                    </Show>
                  </Badge>
                </div>
              )}
            </For>
          }
        </div>
      </Link>
    </div>
  );
}
