// twopi-ui/src/components/TransactionList.vue
<script setup lang="ts">
import type { Paths } from "@/lib/openapi";
import dayjs from "dayjs";

type Transaction = NonNullable<
  Paths["/twopi-api/transaction/{transaction_id}"]["get"]["responses"]["200"]["content"]["application/json"]
>;
const props = defineProps<{
  transactions: Readonly<Transaction[]>;
}>();

const transactions = computed(() =>
  Object.entries(
    Object.groupBy(props.transactions, (transaction) =>
      dayjs(transaction.transaction.timestamp).format("YYYY-MM-DD"),
    ),
  ).toSorted((a, b) => b[0].localeCompare(a[0])),
);
const noTransactions = computed(() => props.transactions.length === 0);
</script>

<template>
  <div class="my-2 flex flex-col gap-3">
    <div v-for="[date, txs] in transactions" :key="date" class="flex flex-col gap-1">
      <div class="font-light text-zinc-700">
        {{ dayjs(date).format("MMM D, YYYY") }}
      </div>
      <TransactionRow
        v-for="transaction in txs?.toSorted((a, b) =>
          b.transaction.timestamp.localeCompare(a.transaction.timestamp),
        )"
        :key="transaction.transaction.id"
        :transaction="transaction"
      />
    </div>
    <div v-if="noTransactions">No transactions found.</div>
  </div>
</template>

// twopi-web/src/components/TransactionList.tsx
import dayjs from "dayjs";
import { For } from "solid-js";
import { type getTransaction } from "~/lib/api/transaction";
import TransactionRow from "./TransactionRow";

type Transaction = Awaited<ReturnType<typeof getTransaction>>;

export default function TransactionList(
  props: Readonly<{ transactions: Transaction[] }>,
) {
  const transactions = () =>
    Object.entries(
      Object.groupBy(props.transactions, (transaction) =>
        dayjs(transaction.transaction.timestamp).format("YYYY-MM-DD"),
      ),
    ).sort((a, b) => b[0].localeCompare(a[0]));

  return (
    <div class="my-2 flex flex-col gap-3">
      {transactions().length === 0 && <div>No transactions found</div>}
      <For each={transactions()}>
        {([date, txs]) => (
          <div class="flex flex-col gap-1">
            <div class="font-light text-zinc-700">
              {dayjs(date).format("MMM D, YYYY")}
            </div>
            {
              <For each={txs}>
                {(transaction) => <TransactionRow transaction={transaction} />}
              </For>
            }
          </div>
        )}
      </For>
    </div>
  );
}
