// twopi-web/app/routes/app/index.tsx
import { useQueries } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import clsx from "clsx";
import { useMemo, useState } from "react";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Line,
  LineChart,
  Rectangle,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import {
  accountQueryOptions,
  currencyRatesQueryOptions,
  transactionQueryOptions,
} from "~/lib/query-options";
import { isDefined } from "~/lib/utils";

export const Route = createFileRoute("/app/")({
  component: RouteComponent,
});

function RouteComponent() {
  const { isPending, data, errors } = useQueries({
    queries: [
      accountQueryOptions(),
      transactionQueryOptions(),
      currencyRatesQueryOptions(),
    ],
    combine: (results) => {
      return {
        data: {
          accounts: results[0].data?.accounts,
          transactions: results[1].data?.transactions,
          currencyRates: results[2].data?.data,
        },
        isPending: results.some((result) => result.isPending),
        errors: results.map((result) => result.error).filter(isDefined),
      };
    },
  });
  const today = new Date();
  const [monthAndYear, setMonthAndYear] = useState({
    month: today.getUTCMonth(),
    year: today.getUTCFullYear(),
  });
  const [currentCurrency, setCurrency] = useState("USD");
  const currenciesToShow = ["USD", "INR", "AED", "CNY", "EUR", "GBP", "JPY"];

  let wealth = 0;
  data.accounts?.forEach((account) => {
    wealth +=
      account.starting_balance /
      (data.currencyRates?.[account.currency.code]?.value ?? 1);
  });
  data.transactions?.forEach((transaction) => {
    transaction.transaction_items.forEach((t) => {
      wealth +=
        t.amount / (data.currencyRates?.[t.account.currency.code]?.value ?? 1);
    });
  });
  const wealthInDifferentCurrencies = currenciesToShow.map((currency) => {
    return {
      currency,
      value: wealth * (data.currencyRates?.[currency]?.value ?? 1),
    };
  });

  const chartData = useMemo(() => {
    const daysInMonth = [];
    daysInMonth.push();
    const date = new Date(Date.UTC(monthAndYear.year, monthAndYear.month, 1));
    while (date.getUTCMonth() === monthAndYear.month) {
      daysInMonth.push(new Date(date));
      date.setDate(date.getUTCDate() + 1);
    }

    let cummulative = 0;
    const categories: { [key: string]: number } = {};

    const wealthData = daysInMonth.map((d) => {
      const dateStart = d.getTime();
      const dateEnd = dateStart + 24 * 60 * 60 * 1000;
      let wealth = 0;
      data.accounts
        ?.filter(
          (account) =>
            dateStart <= new Date(account.created_at).getTime() &&
            new Date(account.created_at).getTime() < dateEnd,
        )
        .forEach((account) => {
          wealth +=
            account.starting_balance /
            (data.currencyRates?.[account.currency.code]?.value ?? 1);
        });
      data.transactions
        ?.filter(
          (transaction) =>
            dateStart <= new Date(transaction.timestamp).getTime() &&
            new Date(transaction.timestamp).getTime() < dateEnd,
        )
        .forEach((transaction) => {
          transaction.transaction_items.forEach((t) => {
            wealth +=
              t.amount /
              (data.currencyRates?.[t.account.currency.code]?.value ?? 1);
          });
        });

      data.transactions
        ?.filter(
          (transaction) =>
            dateStart <= new Date(transaction.timestamp).getTime() &&
            new Date(transaction.timestamp).getTime() < dateEnd,
        )
        .forEach((transaction) => {
          transaction.transaction_items.forEach((t) => {
            if (t.category) {
              categories[t.category.name] =
                (categories[t.category.name] ?? 0) +
                t.amount /
                  (data.currencyRates?.[t.account.currency.code]?.value ?? 1);
            }
          });
        });
      cummulative += wealth;
      return {
        date: `${d.getUTCDate()}`,
        wealth: cummulative,
      };
    });

    return {
      wealthData,
      categories: Object.entries(categories).sort((a, b) => {
        if (a[0] < b[0]) return -1;
        if (a[0] > b[0]) return 1;
        return 0;
      }),
    };
  }, [monthAndYear, data]);

  if (isPending) return "Loading...";

  if (errors.length)
    return (
      <div>
        Error occurred:
        {errors.map((error, i) => (
          <div key={i}>{error.message}</div>
        ))}
      </div>
    );

  return (
    <div className="bg-base-100 flex flex-col gap-4 p-4 shadow-sm">
      <h1 className="text-2xl font-bold">Dashboard</h1>
      <h2 className="text-center text-lg font-bold">Total wealth</h2>
      <div className="flex flex-wrap items-center justify-center gap-4">
        {wealthInDifferentCurrencies.map((wealth) => (
          <div
            key={wealth.currency}
            className={clsx(
              "bg-base-200 p-2 text-2xl shadow-sm",
              wealth.value > 0
                ? "bg-success text-success-content"
                : wealth.value < 0
                  ? "bg-error text-error-content"
                  : "bg-neutral text-neutral-content",
            )}
          >
            {new Intl.NumberFormat("en", {
              style: "currency",
              currency: wealth.currency,
            }).format(wealth.value)}
          </div>
        ))}
      </div>
      <div className="m-4 flex flex-col items-center gap-4">
        <h2 className="text-center text-lg font-bold">
          Wealth chart ({currentCurrency}) for{" "}
          {Intl.DateTimeFormat("en", {
            month: "long",
            year: "numeric",
          }).format(new Date(monthAndYear.year, monthAndYear.month))}
        </h2>
        <div className="flex gap-4">
          <select
            value={currentCurrency}
            onChange={(e) => setCurrency(e.target.value)}
          >
            {currenciesToShow.map((currency) => (
              <option key={currency} value={currency}>
                {currency}
              </option>
            ))}
          </select>
          <select
            value={monthAndYear.month}
            onChange={(e) =>
              setMonthAndYear({
                ...monthAndYear,
                month: Number(e.target.value),
              })
            }
          >
            {Array.from({ length: 12 }, (_, i) => i).map((i) => (
              <option key={i} value={i}>
                {Intl.DateTimeFormat("en", { month: "short" }).format(
                  new Date(0, i),
                )}
              </option>
            ))}
          </select>
          <input
            type="number"
            value={monthAndYear.year}
            onChange={(e) =>
              setMonthAndYear({
                ...monthAndYear,
                year: Number(e.target.value),
              })
            }
          />
        </div>
        <ResponsiveContainer width="100%" height={250}>
          <LineChart
            data={chartData.wealthData.map(({ date, wealth }) => ({
              date,
              wealth:
                wealth * (data.currencyRates?.[currentCurrency]?.value ?? 1),
            }))}
          >
            <Line type="monotone" dataKey="wealth" stroke="#8884d8" />
            <CartesianGrid stroke="#eee" strokeDasharray="3 3" />
            <Tooltip
              labelFormatter={(value) => {
                return Intl.DateTimeFormat("en", {
                  day: "2-digit",
                  month: "short",
                  year: "numeric",
                }).format(
                  new Date(
                    monthAndYear.year,
                    monthAndYear.month,
                    Number(value),
                  ),
                );
              }}
              formatter={(value) => {
                return [
                  Intl.NumberFormat("en", {
                    currency: currentCurrency,
                    style: "currency",
                  }).format(Number(value)),
                ];
              }}
            />
            <XAxis dataKey="date" />
            <YAxis />
          </LineChart>
        </ResponsiveContainer>
        <ResponsiveContainer width="100%" height={500}>
          <BarChart
            width={400}
            height={400}
            data={chartData.categories.map(([name, value]) => ({
              name,
              value:
                value * (data.currencyRates?.[currentCurrency]?.value ?? 1),
            }))}
          >
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis
              dataKey="name"
              interval="preserveStartEnd"
              angle={270}
              textAnchor="end"
              height={150}
            />
            <YAxis />
            <Tooltip
              formatter={(value) => {
                return [
                  Intl.NumberFormat("en", {
                    currency: currentCurrency,
                    style: "currency",
                  }).format(Number(value)),
                ];
              }}
            />
            <Bar
              dataKey="value"
              fill="#8884d8"
              activeBar={<Rectangle fill="pink" stroke="blue" />}
            />
          </BarChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
}

// twopi-web/src/routes/app/index.tsx
import { useQuery } from "@tanstack/solid-query";
import { createFileRoute } from "@tanstack/solid-router";
import { createMemo, createSignal, For, Show } from "solid-js";
import CurrencyDisplay from "~/components/CurrencyDisplay";
import { PageLayout } from "~/components/PageLayout";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "~/components/ui/card";
import { Input } from "~/components/ui/input";
import { Progress } from "~/components/ui/progress";
import {
  Select,
  SelectContent,
  SelectHiddenSelect,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "~/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "~/components/ui/table";
import {
  accountQueryOptions,
  categoryQueryOptions,
  currencyQueryOptions,
  currencyRatesQueryOptions,
  dashboardQueryOptions,
  transactionQueryOptions,
} from "~/lib/query-options";

export const Route = createFileRoute("/app/")({
  component: RouteComponent,
});

function RouteComponent() {
  const currenciesQuery = useQuery(currencyQueryOptions);
  const currencyRatesQuery = useQuery(currencyRatesQueryOptions);
  const dashboardQuery = useQuery(dashboardQueryOptions);
  const accountsQuery = useQuery(accountQueryOptions);
  const categoriesQuery = useQuery(categoryQueryOptions);
  const transactionsQuery = useQuery(transactionQueryOptions);

  const account = (id: string) =>
    accountsQuery.data?.accounts.find((account) => account.account.id === id);
  const category = (id?: string | null) =>
    categoriesQuery.data?.categories.find((category) => category.id === id);

  const [currentCurrency, setCurrentCurrency] = createSignal("USD");
  const currenciesToShow = ["USD", "INR", "AED", "CNY", "EUR", "GBP", "JPY"];
  const currencies =
    currenciesQuery.data?.data?.filter((c) =>
      currenciesToShow.includes(c.code),
    ) ?? [];
  const currentCurrencyData = () =>
    currencies.find((c) => c.code === currentCurrency());

  const today = new Date();
  const [monthAndYear, setMonthAndYear] = createSignal({
    month: today.getUTCMonth(),
    year: today.getUTCFullYear(),
  });

  const wealth = createMemo(() => {
    let wealth = 0;
    accountsQuery.data?.accounts?.forEach((account) => {
      wealth +=
        account.account.starting_balance /
        Math.pow(10, account.currency.decimal_digits) /
        (currencyRatesQuery.data?.data?.[account.currency.code]?.value ?? 1);
    });
    transactionsQuery.data?.transactions?.forEach((transaction) => {
      transaction.items.forEach((t) => {
        wealth +=
          t.amount /
          Math.pow(10, account(t.account_id)?.currency.decimal_digits ?? 2) /
          (currencyRatesQuery.data?.data?.[
            account(t.account_id)?.currency.code ?? "USD"
          ]?.value ?? 1);
      });
    });
    return wealth;
  });

  const chartData = createMemo(() => {
    const daysInMonth = [];
    daysInMonth.push();
    const date = new Date(
      Date.UTC(monthAndYear().year, monthAndYear().month, 1),
    );
    const firstDay = date.getTime();
    while (date.getUTCMonth() === monthAndYear().month) {
      daysInMonth.push(new Date(date));
      date.setDate(date.getUTCDate() + 1);
    }

    let cumulative = 0;
    let cashFlowCumulative = 0;
    const categories: { [key: string]: number } = {};
    accountsQuery.data?.accounts
      ?.filter(
        (account) => new Date(account.account.created_at).getTime() < firstDay,
      )
      .forEach((account) => {
        cumulative +=
          account.account.starting_balance /
          Math.pow(10, account.currency.decimal_digits) /
          (currencyRatesQuery.data?.data?.[account.currency.code]?.value ?? 1);
        if (account.account.is_cash_flow) {
          cashFlowCumulative +=
            account.account.starting_balance /
            Math.pow(10, account.currency.decimal_digits) /
            (currencyRatesQuery.data?.data?.[account.currency.code]?.value ??
              1);
        }
      });
    transactionsQuery.data?.transactions
      ?.filter(
        (transaction) =>
          new Date(transaction.transaction.timestamp).getTime() < firstDay,
      )
      .forEach((transaction) => {
        transaction.items.forEach((t) => {
          cumulative +=
            t.amount /
            Math.pow(10, account(t.account_id)?.currency.decimal_digits ?? 2) /
            (currencyRatesQuery.data?.data[
              account(t.account_id)?.currency.code ?? "USD"
            ]?.value ?? 1);
          if (account(t.account_id)?.account.is_cash_flow) {
            cashFlowCumulative +=
              t.amount /
              Math.pow(
                10,
                account(t.account_id)?.currency.decimal_digits ?? 2,
              ) /
              (currencyRatesQuery.data?.data[
                account(t.account_id)?.currency.code ?? "USD"
              ]?.value ?? 1);
          }
        });
      });

    const wealthData = daysInMonth.map((d) => {
      const dateStart = d.getTime();
      const dateEnd = dateStart + 24 * 60 * 60 * 1000;
      let wealth = 0;
      let cashFlow = 0;
      accountsQuery.data?.accounts
        ?.filter(
          (account) =>
            dateStart <= new Date(account.account.created_at).getTime() &&
            new Date(account.account.created_at).getTime() < dateEnd,
        )
        .forEach((account) => {
          wealth +=
            account.account.starting_balance /
            Math.pow(10, account.currency.decimal_digits) /
            (currencyRatesQuery.data?.data[account.currency.code]?.value ?? 1);
          if (account.account.is_cash_flow) {
            cashFlow +=
              account.account.starting_balance /
              Math.pow(10, account.currency.decimal_digits) /
              (currencyRatesQuery.data?.data[account.currency.code]?.value ??
                1);
          }
        });
      transactionsQuery.data?.transactions
        ?.filter(
          (transaction) =>
            dateStart <=
              new Date(transaction.transaction.timestamp).getTime() &&
            new Date(transaction.transaction.timestamp).getTime() < dateEnd,
        )
        .forEach((transaction) => {
          transaction.items.forEach((t) => {
            const amount =
              t.amount /
              Math.pow(
                10,
                account(t.account_id)?.currency.decimal_digits ?? 2,
              ) /
              (currencyRatesQuery.data?.data[
                account(t.account_id)?.currency.code ?? "USD"
              ]?.value ?? 1);
            if (t.category_id) {
              categories[category(t.category_id)?.name ?? ""] =
                (categories[category(t.category_id)?.name ?? ""] ?? 0) + amount;
            }
            wealth += amount;
            if (account(t.account_id)?.account.is_cash_flow) {
              cashFlow += amount;
            }
          });
        });

      cumulative += wealth;
      cashFlowCumulative += cashFlow;
      return {
        date: `${d.getUTCDate()}`,
        wealth: cumulative,
        cashFlow: cashFlowCumulative,
      };
    });

    return {
      wealthData,
    };
  });

  const current_month = createMemo(() => dashboardQuery.data?.last_3m?.[2]);
  const prev_month = createMemo(() => dashboardQuery.data?.last_3m?.[1]);
  const prev_prev_month = createMemo(() => dashboardQuery.data?.last_3m?.[0]);

  const categories = createMemo(() =>
    Object.entries(dashboardQuery.data?.categoies_last_3m ?? {})
      .map(([name, value]) => {
        const current_value = Object.entries(value[2] ?? {}).reduce(
          (acc, [currency, value]) =>
            acc +
            value / (currencyRatesQuery.data?.data?.[currency]?.value ?? 1),
          0,
        );
        const prev_value = Object.entries(value[1] ?? {}).reduce(
          (acc, [currency, value]) =>
            acc +
            value / (currencyRatesQuery.data?.data?.[currency]?.value ?? 1),
          0,
        );
        const prev_prev_value = Object.entries(value[0] ?? {}).reduce(
          (acc, [currency, value]) =>
            acc +
            value / (currencyRatesQuery.data?.data?.[currency]?.value ?? 1),
          0,
        );
        return {
          name,
          current_value,
          prev_value,
          prev_prev_value,
        };
      })
      .toSorted((a, b) => (a.name < b.name ? -1 : 1)),
  );

  return (
    <PageLayout
      title="Dashboard"
      actions={
        <>
          <Select
            options={Array.from({ length: 12 }, (_, i) => i)}
            value={String(monthAndYear().month)}
            onChange={(e) =>
              setMonthAndYear({
                ...monthAndYear(),
                month: Number(e),
              })
            }
            itemComponent={(props) => (
              <SelectItem item={props.item}>
                {Intl.DateTimeFormat("en", { month: "short" }).format(
                  new Date(0, Number(props.item.rawValue)),
                )}
              </SelectItem>
            )}
          >
            <SelectHiddenSelect />
            <SelectTrigger>
              <SelectValue<string>>
                {(state) =>
                  Intl.DateTimeFormat("en", { month: "short" }).format(
                    new Date(0, Number(state.selectedOption())),
                  )
                }
              </SelectValue>
            </SelectTrigger>
            <SelectContent />
          </Select>
          <Input
            type="number"
            value={monthAndYear().year}
            onChange={(e) =>
              setMonthAndYear({
                ...monthAndYear(),
                year: Number(e.target.value),
              })
            }
          />
          <Select
            options={currenciesToShow}
            value={currentCurrency()}
            placeholder="Select account type"
            onChange={setCurrentCurrency}
            itemComponent={(props) => (
              <SelectItem item={props.item}>{props.item.rawValue}</SelectItem>
            )}
          >
            <SelectHiddenSelect />
            <SelectTrigger>
              <SelectValue<string>>
                {(state) => state.selectedOption()}
              </SelectValue>
            </SelectTrigger>
            <SelectContent />
          </Select>
        </>
      }
    >
      <h2 class="text-center text-lg font-bold">Total wealth</h2>
      <div class="mb-4 flex flex-wrap items-center justify-center gap-4">
        <div class="bg-accent shadow-xs p-2 text-2xl">
          <CurrencyDisplay
            value={
              wealth() *
              (currencyRatesQuery.data?.data?.[currentCurrency()]?.value ?? 1) *
              Math.pow(10, currentCurrencyData()?.decimal_digits ?? 0)
            }
            currencyCode={currentCurrency()}
            decimalDigits={currentCurrencyData()?.decimal_digits ?? 0}
          />
        </div>
      </div>
      <div class="flex w-full flex-col gap-4">
        <Card>
          <CardHeader>
            <CardTitle>Wealth</CardTitle>
            <CardDescription>
              {Intl.DateTimeFormat("en", {
                month: "long",
                year: "numeric",
              }).format(new Date(monthAndYear().year, monthAndYear().month))}
            </CardDescription>
          </CardHeader>
          <CardContent>
            <pre class="max-h-64 overflow-auto">
              {JSON.stringify(
                chartData().wealthData.map(({ date, wealth, cashFlow }) => ({
                  date: Intl.DateTimeFormat("en", {
                    day: "2-digit",
                    month: "short",
                    year: "numeric",
                  }).format(
                    new Date(
                      monthAndYear().year,
                      monthAndYear().month,
                      Number(date),
                    ),
                  ),
                  wealth: Intl.NumberFormat("en", {
                    currency: currentCurrency(),
                    style: "currency",
                  }).format(
                    wealth *
                      (currencyRatesQuery.data?.data[currentCurrency()]
                        ?.value ?? 1),
                  ),
                  cashFlow: Intl.NumberFormat("en", {
                    currency: currentCurrency(),
                    style: "currency",
                  }).format(
                    cashFlow *
                      (currencyRatesQuery.data?.data[currentCurrency()]
                        ?.value ?? 1),
                  ),
                })),
                null,
                2,
              )}
            </pre>
          </CardContent>
          <CardFooter>Cumulative wealth over the month</CardFooter>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Cash Flow</CardTitle>
            <CardDescription>
              {Intl.DateTimeFormat("en", {
                month: "long",
                year: "numeric",
              }).format(new Date(monthAndYear().year, monthAndYear().month))}
            </CardDescription>
          </CardHeader>
          <CardContent>
            <pre class="max-h-64 overflow-auto">
              {JSON.stringify(
                chartData().wealthData.map(({ date, wealth, cashFlow }) => ({
                  date: Intl.DateTimeFormat("en", {
                    day: "2-digit",
                    month: "short",
                    year: "numeric",
                  }).format(
                    new Date(
                      monthAndYear().year,
                      monthAndYear().month,
                      Number(date),
                    ),
                  ),
                  wealth: Intl.NumberFormat("en", {
                    currency: currentCurrency(),
                    style: "currency",
                  }).format(
                    wealth *
                      (currencyRatesQuery.data?.data[currentCurrency()]
                        ?.value ?? 1),
                  ),
                  cashFlow: Intl.NumberFormat("en", {
                    currency: currentCurrency(),
                    style: "currency",
                  }).format(
                    cashFlow *
                      (currencyRatesQuery.data?.data[currentCurrency()]
                        ?.value ?? 1),
                  ),
                })),
                null,
                2,
              )}
            </pre>
          </CardContent>
          <CardFooter>Cumulative cash flow over the month</CardFooter>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Categories Table</CardTitle>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Category</TableHead>
                  <TableHead class="text-right">
                    Amount (
                    <Show when={prev_prev_month()}>
                      {(prev_prev_month) =>
                        Intl.DateTimeFormat("en", {
                          month: "long",
                          year: "numeric",
                        }).format(
                          new Date(
                            prev_prev_month()?.[1],
                            prev_prev_month()?.[0] - 1,
                          ),
                        )
                      }
                    </Show>
                    )
                  </TableHead>
                  <TableHead class="text-right">
                    Amount (
                    <Show when={prev_month()}>
                      {(prev_month) =>
                        Intl.DateTimeFormat("en", {
                          month: "long",
                          year: "numeric",
                        }).format(
                          new Date(prev_month()?.[1], prev_month()?.[0] - 1),
                        )
                      }
                    </Show>
                    )
                  </TableHead>
                  <TableHead class="text-right">
                    Amount (
                    <Show when={current_month()}>
                      {(current_month) =>
                        Intl.DateTimeFormat("en", {
                          month: "long",
                          year: "numeric",
                        }).format(
                          new Date(
                            current_month()?.[1],
                            current_month()?.[0] - 1,
                          ),
                        )
                      }
                    </Show>
                    )
                  </TableHead>
                  <TableHead />
                </TableRow>
              </TableHeader>
              <TableBody>
                <For each={categories()}>
                  {({ name, current_value, prev_value, prev_prev_value }) => (
                    <TableRow>
                      <TableCell>{category(name)?.name}</TableCell>
                      <TableCell class="text-right">
                        <CurrencyDisplay
                          value={
                            prev_prev_value *
                            (currencyRatesQuery.data?.data?.[currentCurrency()]
                              ?.value ?? 1) *
                            Math.pow(
                              10,
                              currentCurrencyData()?.decimal_digits ?? 0,
                            )
                          }
                          currencyCode={currentCurrency()}
                          decimalDigits={
                            currentCurrencyData()?.decimal_digits ?? 0
                          }
                        />
                      </TableCell>
                      <TableCell class="text-right">
                        <CurrencyDisplay
                          value={
                            prev_value *
                            (currencyRatesQuery.data?.data?.[currentCurrency()]
                              ?.value ?? 1) *
                            Math.pow(
                              10,
                              currentCurrencyData()?.decimal_digits ?? 0,
                            )
                          }
                          currencyCode={currentCurrency()}
                          decimalDigits={
                            currentCurrencyData()?.decimal_digits ?? 0
                          }
                        />
                      </TableCell>
                      <TableCell class="text-right">
                        <CurrencyDisplay
                          value={
                            current_value *
                            (currencyRatesQuery.data?.data?.[currentCurrency()]
                              ?.value ?? 1) *
                            Math.pow(
                              10,
                              currentCurrencyData()?.decimal_digits ?? 0,
                            )
                          }
                          currencyCode={currentCurrency()}
                          decimalDigits={
                            currentCurrencyData()?.decimal_digits ?? 0
                          }
                        />
                      </TableCell>
                      <TableCell class="w-1/6">
                        <Progress
                          value={
                            Math.abs(current_value * 100) /
                            Math.max(
                              ...categories().map((c) =>
                                Math.abs(c.current_value),
                              ),
                            )
                          }
                        />
                      </TableCell>
                    </TableRow>
                  )}
                </For>
                <TableRow>
                  <TableCell class="font-semibold">Total</TableCell>
                  <TableCell class="text-right font-semibold">
                    <CurrencyDisplay
                      value={
                        categories().reduce(
                          (acc, c) => acc + c.prev_prev_value,
                          0,
                        ) *
                        (currencyRatesQuery.data?.data?.[currentCurrency()]
                          ?.value ?? 1) *
                        Math.pow(10, currentCurrencyData()?.decimal_digits ?? 0)
                      }
                      currencyCode={currentCurrency()}
                      decimalDigits={currentCurrencyData()?.decimal_digits ?? 0}
                    />
                  </TableCell>
                  <TableCell class="text-right font-semibold">
                    <CurrencyDisplay
                      value={
                        categories().reduce((acc, c) => acc + c.prev_value, 0) *
                        (currencyRatesQuery.data?.data?.[currentCurrency()]
                          ?.value ?? 1) *
                        Math.pow(10, currentCurrencyData()?.decimal_digits ?? 0)
                      }
                      currencyCode={currentCurrency()}
                      decimalDigits={currentCurrencyData()?.decimal_digits ?? 0}
                    />
                  </TableCell>
                  <TableCell class="text-right font-semibold">
                    <CurrencyDisplay
                      value={
                        categories().reduce(
                          (acc, c) => acc + c.current_value,
                          0,
                        ) *
                        (currencyRatesQuery.data?.data?.[currentCurrency()]
                          ?.value ?? 1) *
                        Math.pow(10, currentCurrencyData()?.decimal_digits ?? 0)
                      }
                      currencyCode={currentCurrency()}
                      decimalDigits={currentCurrencyData()?.decimal_digits ?? 0}
                    />
                  </TableCell>
                  <TableCell />
                </TableRow>
              </TableBody>
            </Table>
          </CardContent>
          <CardFooter>Income/Expense in each category</CardFooter>
        </Card>
      </div>
    </PageLayout>
  );
}
