// twopi-ui/src/pages/app/settings.vue
<script setup lang="ts">
import { useResetAccount } from "@/lib/auth";
import { useRouter } from "vue-router";

const { mutateAsync, error } = useResetAccount();
const router = useRouter();

const open = ref(false);

async function handleReset() {
  const response = await mutateAsync();
  if (response.success) {
    open.value = false;
    router.push({
      name: "/",
    });
  }
}
</script>

<template>
  <AppPage title="Settings">
    <div>
      <p>Manage your account settings here.</p>
      <UModal v-model:open="open" title="Reset Account">
        <UButton class="mt-4" color="error"> Reset Account </UButton>
        <template #body>
          <p>This action will reset your account and delete all data. Are you sure?</p>
          <p v-if="error" class="text-error mt-2">{{ error.message }}</p>
          <UButton class="mr-2 mt-2" color="error" @click="handleReset"> Reset</UButton>
          <UButton class="mt-2" @click="open = false">Cancel</UButton>
        </template>
      </UModal>
    </div>
  </AppPage>
</template>

// twopi-web/src/routes/app/settings.tsx
import { createFileRoute, useRouter } from "@tanstack/solid-router";
import { createSignal } from "solid-js";
import { PageLayout } from "~/components/PageLayout";
import {
  AlertDialog,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "~/components/ui/alert-dialog";
import { Button } from "~/components/ui/button";
import { apiClient } from "~/lib/openapi";

export const Route = createFileRoute("/app/settings")({
  component: RouteComponent,
});

async function resetAccount() {
  const { data, error } = await apiClient.POST("/twopi-api/api/reset-account");
  if (error) {
    throw new Error(error);
  }
  return data;
}

function RouteComponent() {
  const router = useRouter();
  const [error, setError] = createSignal<string | null>(null);
  const [open, setOpen] = createSignal(false);

  async function onClickReset() {
    setError(null);
    try {
      await resetAccount();
      router.navigate({
        to: "/",
      });
    } catch (error) {
      if (error instanceof Error) {
        setError(error.message);
      }
      console.error(error);
    } finally {
      setOpen(false);
    }
  }

  return (
    <PageLayout title="Settings">
      <div>
        <AlertDialog open={open()} onOpenChange={setOpen}>
          <AlertDialogTrigger>
            <Button variant="destructive">Reset data</Button>
          </AlertDialogTrigger>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>Are you absolutely sure?</AlertDialogTitle>
              <AlertDialogDescription>
                This action cannot be undone. This will permanently delete your
                data.
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <Button variant="secondary" onClick={() => setOpen(false)}>
                Cancel
              </Button>
              <Button variant="destructive" onClick={() => onClickReset()}>
                Continue
              </Button>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
        {error && <p class="text-destructive">{error()}</p>}
      </div>
    </PageLayout>
  );
}
